imports:
  - { resource: TemplateLogic/services.yaml }
  - { resource: Translator/services.yaml }

services:
  _defaults:
    autowire: true

  OxidEsales\EshopCommunity\Internal\Transition\Adapter\ShopAdapterInterface:
    class: OxidEsales\EshopCommunity\Internal\Transition\Adapter\ShopAdapter

  OxidEsales\EshopCommunity\Internal\Framework\Config\Dao\ShopConfigurationSettingDaoInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Config\Dao\ShopConfigurationSettingDao

  OxidEsales\EshopCommunity\Internal\Framework\Config\Utility\ShopSettingEncoderInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Config\Utility\ShopSettingEncoder
